#!/bin/bash -ex

URL="http://pkg.jenkins-ci.org/debian-stable"
NAME="jenkins"

mkdir -p /usr/share/keyrings
wget -q -O - $URL/jenkins-ci.org.key | gpg --dearmor > /usr/share/keyrings/jenkins.gpg

cat >/etc/apt/sources.list.d/$NAME.list<<EOF
deb [signed-by=/usr/share/keyrings/jenkins.gpg] $URL binary/
EOF

cat >/etc/apt/preferences.d/$NAME<<EOF
Package: *
Pin: release o=jenkins-ci.org
Pin-Priority: 100

Package: $NAME
Pin: release o=jenkins-ci.org
Pin-Priority: 500
EOF

apt-get -y update

for i in openjdk-8-jdk ant $NAME; do
    DEBIAN_FRONTEND=noninteractive apt-get --force-yes --assume-yes install $i
done

sleep 5
service jenkins stop

