#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

# non-default plugins to install and/or default plugins to update
PLUGINS="
jsch
apache-httpcomponents-client-4-api
workflow-api
scm-api
structs
git
workflow-step-api
workflow-scm-step
credentials
git-client
ssh-credentials
matrix-project
pam-auth
junit
script-security
mailer
display-url-api
bouncycastle-api
command-launcher
jdk-tool
echarts-api
jaxb
trilead-api
jackson2-api
jquery3-api
plugin-util-api
snakeyaml-api
"
PLUGINS_DIR="/var/lib/jenkins/plugins"
mkdir -p $PLUGINS_DIR

for plugin in $PLUGINS; do
    dl https://updates.jenkins-ci.org/latest/${plugin}.hpi $PLUGINS_DIR
done

# disable cvs plugin (subsystem not included ootb)
if [ -e $PLUGINS_DIR/cvs.jpi ]; then
    mv $PLUGINS_DIR/cvs.jpi $PLUGINS_DIR/cvs.jpi.disabled
fi

chown -R jenkins:nogroup $PLUGINS_DIR

# skip setup wizard
JENKINS_VER=$(java -jar /usr/share/jenkins/jenkins.war --version)
echo -n "$JENKINS_VER" > /var/lib/jenkins/jenkins.install.UpgradeWizard.state
echo -n "$JENKINS_VER" > /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
