#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

PLUGINS="git git-client bazaar mercurial"
PLUGINS_DIR="/var/lib/jenkins/plugins"
mkdir -p $PLUGINS_DIR

for plugin in $PLUGINS; do
    dl https://updates.jenkins-ci.org/latest/${plugin}.hpi $PLUGINS_DIR
done

mv $SRC/page-markup.jpi $PLUGINS_DIR
mv $SRC/hudson.plugins.page_markup.PageMarkupPageDecorator.xml /var/lib/jenkins

# disable cvs plugin (subsystem not included ootb)
if [ -e $PLUGINS_DIR/cvs.jpi ]; then
    mv $PLUGINS_DIR/cvs.jpi $PLUGINS_DIR/cvs.jpi.disabled
fi

chown -R jenkins:nogroup $PLUGINS_DIR
chown jenkins:nogroup /var/lib/jenkins/*.xml

