#!/bin/bash -ex

# set cli for easy local use

service apache2 start
service jenkins start

CLI_PATH=/usr/local/share/jenkins/jenkins-cli.jar

mkdir -p /usr/local/share/jenkins

while true; do
    curl -k -o "$CLI_PATH" 'https://localhost/jnlpJars/jenkins-cli.jar'
    file "$CLI_PATH"
    if file "$CLI_PATH" | grep JAR; then
        break
    fi
    sleep 2
done

JENKINS_HOME=/var/lib/jenkins

cat > /usr/local/bin/jenkins-cli <<EOF
#!/bin/bash -e

java -jar $CLI_PATH \$@

EOF

chmod +x /usr/local/bin/jenkins-cli

cat > /root/.bashrc.d/jenkins <<EOF
export JENKINS_URL=http://localhost:8080
export JENKINS_HOME=$JENKINS_HOME
EOF

chmod +x /root/.bashrc.d/jenkins

# disable -remoting mode (security)

cat > $JENKINS_HOME/jenkins.CLI.xml <<EOF
<?xml version='1.0' encoding='UTF-8'?>
<jenkins.CLI>
  <enabled>false</enabled>
</jenkins.CLI>
EOF

service apache2 stop
service jenkins stop
