#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    # forcing http1 because jenkins seems to cause lots of HTTP2 framing errors
    cd $2; curl --http1.1 -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src

# non-default plugins to install and/or default plugins to update
PLUGINS="
workflow-support
jsch
scm-api
structs
git
workflow-scm-step
credentials
git-client
ssh-credentials
matrix-project
junit
script-security
mailer
command-launcher
jdk-tool
jaxb
credentials-binding
"
PLUGINS_DIR="/var/lib/jenkins/plugins"
mkdir -p $PLUGINS_DIR

service jenkins start

while true; do
    if jenkins-cli -s http://localhost:8080/ -auth jenkins-admin:turnkey; then
        break
    fi
    sleep 2
done

for plugin in $PLUGINS; do
    jenkins-cli -s http://localhost:8080/ -auth jenkins-admin:turnkey install-plugin "$plugin"
done

# disable cvs plugin (subsystem not included ootb)
if [ -e $PLUGINS_DIR/cvs.jpi ]; then
    mv $PLUGINS_DIR/cvs.jpi $PLUGINS_DIR/cvs.jpi.disabled
fi

chown -R jenkins:nogroup $PLUGINS_DIR

# skip setup wizard
JENKINS_VER=$(java -jar /usr/share/java/jenkins.war --version)
echo -n "$JENKINS_VER" > /var/lib/jenkins/jenkins.install.UpgradeWizard.state
echo -n "$JENKINS_VER" > /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
service jenkins stop
