#!/bin/sh -ex

SRC=/usr/local/src
WEBAPPS=/var/lib/tomcat6/webapps
JHOME=/var/local/lib/jenkins

# configure jenkins
rm -rf $WEBAPPS/ROOT
mv $SRC/jenkins-*.war $WEBAPPS/jenkins.war

# configure jenkins home
chown -R tomcat6:tomcat6 $JHOME
echo "export JENKINS_HOME=$JHOME" >> /etc/environment
sed -i "s|CATALINA_OPTS=\"|CATALINA_OPTS=\"-DJENKINS_HOME=$JHOME |" /etc/environment

